project: 
  type: manuscript
  output-dir: docs
  
manuscript: 
  article: Lab_7.qmd
  
title: "Lab_7"
bibliography: references.bib
csl: apa-6th-edition.csl
  
author:
  - name: "Ainsley Denham"
    corresponding: true 
  - name: "Melissa May"
  - name: "Ava Madalinski"
  
format: 
  html: 
    comments: 
      hypothesis: true
    docx: default 
    jats: default
    
execute: 
  freeze: true
    